# ==============================================================================
# freezeout2d.jl — P9: a 2-D freeze-out surface and Cooper-Frye pion yield.
#
#   julia -t auto --project=Julia Julia/FiVoHydro.jl/freezeout2d.jl [tag ...]
#
# The 2-D initial conditions inherit their normalisation from the 1-D pipeline
# through a density -> T map (BuildIC2D.jl header): `TemperatureCalibration.jl`
# tunes `Norm` until the 1-D Cooper-Frye pion yield matches ALICE
# (N_pi_final = 1339.63 against N_alice = 1340), and the 2-D build reuses that
# calibrated T(r) without ever re-deriving it in 2-D. Doing so needs a 2-D
# freeze-out surface, which did not exist. This is it.
#
# ---------------------------------------------------------------------------
# THE SURFACE
#
# Boost-invariant, so the surface is generated by a curve in (tau, x, y) extended
# over all eta. Parameterised as tau = tau_fo(x, y): for each transverse cell the
# LAST time T crosses T_fo downwards. Then
#
#   dSigma_mu = tau_fo (1, -d_x tau_fo, -d_y tau_fo, 0) dx dy deta
#
# ⚠ A single-valued tau_fo(x,y) cannot represent a surface that folds back in
# time. `FreezeOutContour.jl` documents exactly that failure in 1-D: for a small
# fireball the centre cools below T_fo while a hot shell survives, and a bijective
# r_fo(tau) discards 26% of the surface. In (x,y) parameterisation the analogous
# failure is a cell that re-heats above T_fo after freezing; the count of such
# cells is REPORTED, so the approximation is measured rather than assumed.
#
# THE YIELD, matching the 1-D pipeline's conventions exactly:
#   m_pi = 0.138, T_fo = 0.156, p_T in [0.1, 5.0] (so sub-100 MeV pions are
#   excluded there too), and pion_yield_factor = 2.0*2.5 = 5.0 folded in at the
#   end (2 for pi+ + pi-, 2.5 for feed-down).
#
#   dN/dy = f_yield/(2 pi)^3 * int dSigma_mu p^mu  f(E*/T_fo)
#   E*    = u^tau m_T cosh(eta) - u^x p_T cos(phi) - u^y p_T sin(phi)
#
# Bose and Boltzmann are BOTH computed, because which one the 1-D pipeline uses
# is not documented and the axisymmetric control below is what decides it.
# ==============================================================================

using Printf, Statistics
const _ROOT = @__DIR__
include(joinpath(_ROOT, "main.jl"))
include(joinpath(_ROOT, "main2D.jl"))
using .hydro
using .hydro2d
const H = hydro2d

const DATA  = normpath(joinpath(_ROOT, "..", "Projects", "ALICE_IC_Creation", "PbPb", "data"))
const T_FO  = 0.156
const M_PI  = 0.138
const FYIELD = 2.0*2.5
const PT_LO, PT_HI = 0.1, 5.0
# ⚠ (hbar c)^3. dSigma_mu p^mu carries fm^3*GeV and d^3p/E = pt dpt dphi deta
# carries GeV^2, so the integrand is fm^3 GeV^3 and the phase-space measure is
# (2 pi hbar c)^3, not (2 pi)^3. Omitting it makes dN/dy 130x too small -- the
# first run of this file returned 8.8 instead of ~1300.
const HBARC = 0.1973269804

"""Evolve and record tau_fo(x,y) and the flow there."""
function freeze_surface(tag; N = 200, box = 18.0, dτ = 0.05, τmax = 16.0,
                        ηs = 0.10, ζs = 0.10)
    g = H.make_grid2d(N, N; xmax = box, ymax = box)
    m = H.build_model_2d(; eos = H.LatticeHRGEOS(),
        enable_shear = true, eta_over_s = ηs, tauShear_coeff = 0.2, deltaShear_factor = 4/3,
        enable_bulk  = true, zeta_over_s = ζs, tauPi_coeff = 15.0,
        enable_diff  = true, kappa_coeff = 0.1163, tauN_coeff = 1.0, pi_clip_factor = 1.0)
    U = H.allocate_state(g, m); wk = H.make_work(g, m)
    if tag == "axisym"
        # THE CONTROL: the same radial profile the 1-D calibration itself used, so
        # a 2-D Cooper-Frye that is convention-compatible must return 1339.63.
        itpT, itpF, _, _ = hydro.load_initial_interpolants(
            joinpath(_ROOT, "data", "initial_profiles_physical.csv");
            fugacity_kind = :alpha, taper_width = 1.0, interp_kind = :linear)
        for ix in 1:g.Nxtot, iy in 1:g.Nytot
            r = hypot(g.xC[ix], g.yC[iy])
            H.set_cell!(U, H.lin(g, ix, iy), Float64(itpT(r)), Float64(itpF(r)),
                        0.0, 0.0, 0.4, m)
        end
        H.finalize_ic!(U, g, m; τ0 = 0.4)
    else
        H.initialize_from_grid_csv!(U, g, m, 0.4, joinpath(DATA, "ic2d_$(tag).csv"))
    end
    ng = g.nghost
    nx, ny = g.Nx, g.Ny
    τfo = fill(NaN, nx, ny); uxf = zeros(nx, ny); uyf = zeros(nx, ny)
    wasabove = falses(nx, ny); refroze = 0
    τ = 0.4
    H.rhs_2d!(wk.k, U, g, τ, m, wk)
    record!(τ) = begin
        for a in 1:nx, b in 1:ny
            i = H.lin(g, ng+a, ng+b); T = exp(wk.yT[i])
            if T > T_FO
                if !isnan(τfo[a,b]); refroze += 1; end
                wasabove[a,b] = true; τfo[a,b] = NaN          # still hot
            elseif wasabove[a,b] && isnan(τfo[a,b])
                τfo[a,b] = τ; uxf[a,b] = wk.ux[i]; uyf[a,b] = wk.uy[i]
            end
        end
    end
    record!(τ)
    while τ < τmax - 1e-9
        r = H.run_sim_2d!(U, g, m; τ0 = τ, τfinal = min(τ+dτ, τmax),
                          CFL = 0.15, CFLτ = 0.05, work = wk)
        @assert r.ok; τ = r.τ; H.update_primitives_2d!(U, g, τ, m, wk)
        record!(τ)
    end
    nhot = count(wasabove); nfroze = count(!isnan, τfo)
    xs = [g.xC[ng+a] for a in 1:nx]; ys = [g.yC[ng+b] for b in 1:ny]
    @printf("  %-12s cells that were ever hot %6d | froze by tau=%.1f %6d | still hot %4d | re-heated after freezing %5d\n",
            tag, nhot, τmax, nfroze, nhot-nfroze, refroze)
    return (; xs, ys, τfo, uxf, uyf, dx = g.dx, nhot, nfroze, refroze)
end

"""Cooper-Frye on tau = tau_fo(x,y). Returns (N_boltzmann, N_bose, neg_fraction)."""
function pion_yield(s; nη = 40, npt = 40, nφ = 24, ηmax = 6.0)
    xs, ys, τfo, uxf, uyf, dx = s.xs, s.ys, s.τfo, s.uxf, s.uyf, s.dx
    nx, ny = length(xs), length(ys)
    ηg = range(-ηmax, ηmax; length = nη); dη = step(ηg)
    ptg = range(PT_LO, PT_HI; length = npt); dpt = step(ptg)
    φg = range(0, 2π*(1-1/nφ); length = nφ); dφ = 2π/nφ
    tot = Threads.Atomic{Float64}(0.0); totB = Threads.Atomic{Float64}(0.0)
    negc = Threads.Atomic{Float64}(0.0); posc = Threads.Atomic{Float64}(0.0)
    Threads.@threads for a in 2:(nx-1)
        acc = 0.0; accB = 0.0; neg = 0.0; pos = 0.0
        for b in 2:(ny-1)
            isnan(τfo[a,b]) && continue
            # gradients of tau_fo; skip a cell whose neighbours never froze
            (isnan(τfo[a-1,b]) || isnan(τfo[a+1,b]) ||
             isnan(τfo[a,b-1]) || isnan(τfo[a,b+1])) && continue
            dxt = (τfo[a+1,b] - τfo[a-1,b])/(2dx)
            dyt = (τfo[a,b+1] - τfo[a,b-1])/(2dx)
            τ = τfo[a,b]; ux = uxf[a,b]; uy = uyf[a,b]
            uτ = sqrt(1 + ux*ux + uy*uy)
            for pt in ptg
                mT = sqrt(pt*pt + M_PI*M_PI)
                for φ in φg
                    px = pt*cos(φ); py = pt*sin(φ)
                    for η in ηg
                        ch = cosh(η)
                        dSp = τ*(mT*ch - dxt*px - dyt*py)
                        Es  = uτ*mT*ch - ux*px - uy*py
                        x   = Es/T_FO
                        fB  = exp(-x)                       # Boltzmann
                        fb  = x > 1e-8 ? 1/(exp(x) - 1) : 0.0   # Bose
                        w   = dSp*pt*dpt*dφ*dη*dx*dx
                        acc  += w*fB; accB += w*fb
                        if dSp < 0; neg += -w*fB; else; pos += w*fB; end
                    end
                end
            end
        end
        Threads.atomic_add!(tot, acc); Threads.atomic_add!(totB, accB)
        Threads.atomic_add!(negc, neg); Threads.atomic_add!(posc, pos)
    end
    pref = FYIELD/(2π*HBARC)^3
    return (pref*tot[], pref*totB[], negc[]/max(posc[]+negc[], 1e-30))
end

function main()
    tags = isempty(ARGS) ? ["axisym", "00-05", "20-30", "30-40"] : ARGS
    println("### 2-D freeze-out surface and Cooper-Frye pion yield")
    println("    1-D calibration: N_pi_final = 1339.63 vs N_alice = 1340 (0-5%)\n")
    for tag in tags
        s = freeze_surface(tag)
        t0 = time()
        NB, Nb, negf = pion_yield(s)
        @printf("  %-12s dN_pi/dy: Boltzmann %8.2f | Bose %8.2f | negative-dSigma fraction %.4f | %5.1fs\n\n",
                tag, NB, Nb, negf, time()-t0); flush(stdout)
    end
end
main()
