#!/usr/bin/env julia
# tools/list_env_flags.jl — enumerate every ENV variable the FiVoHydro sources read, with the
# default the code falls back to and the file:line of the read. Output is a Markdown table
# (written to ENV_FLAGS.md) so the documented list cannot drift from the code.
#
#   julia Julia/FiVoHydro.jl/tools/list_env_flags.jl            # Markdown table to stdout
#   julia Julia/FiVoHydro.jl/tools/list_env_flags.jl --count    # just the number of distinct flags
#
# Recognised idioms (all of them occur in the sources):
#   get(ENV, "NAME", default)     haskey(ENV, "NAME")     ENV["NAME"]
#   env_float("NAME", default) / env_int / env_str / env_bool / env_maybe_float   (main.jl `main()`)
#   env_bool_default("NAME", default) etc. (src/runtime_flags.jl)
const ROOT = normpath(joinpath(@__DIR__, ".."))
const SKIP = ("tools/list_env_flags.jl",)

files = String[]
for (d, _, fs) in walkdir(ROOT)
    occursin(r"[/\\](\.git|snapshots|debug_\w+)([/\\]|$)", d) && continue
    for f in fs
        endswith(f, ".jl") || continue
        rel = relpath(joinpath(d, f), ROOT)
        rel in SKIP && continue
        push!(files, rel)
    end
end
sort!(files)

# name => [(file:line, default, context)]
const PAT = r"""(?:get\(\s*ENV\s*,\s*"(?<g>[A-Z][A-Z0-9_]*)"\s*,\s*(?<gd>[^)]*?)\)|haskey\(\s*ENV\s*,\s*"(?<h>[A-Z][A-Z0-9_]*)"\s*\)|ENV\[\s*"(?<b>[A-Z][A-Z0-9_]*)"\s*\]|env_(?:float|int|str|bool|maybe_float|bool_default|int_default|float_default|string_default)\(\s*"(?<e>[A-Z][A-Z0-9_]*)"\s*(?:,\s*(?<ed>[^)]*?))?\))"""
hits = Dict{String,Vector{Tuple{String,String,String}}}()
for rel in files
    for (ln, line) in enumerate(eachline(joinpath(ROOT, rel)))
        startswith(strip(line), "#") && continue
        for m in eachmatch(PAT, line)
            name = something(m[:g], m[:h], m[:b], m[:e], "")
            isempty(name) && continue
            dflt = something(m[:gd], m[:ed], "")
            push!(get!(hits, name, Tuple{String,String,String}[]), ("$rel:$ln", strip(dflt), strip(line)))
        end
    end
end

if "--count" in ARGS
    println(length(hits)); exit(0)
end

# group by file of first read so the table reads top-down by solver
println("| flag | default | read at | read in |")
println("|---|---|---|---|")
for name in sort!(collect(keys(hits)))
    hs = hits[name]
    dflt = let ds = unique(filter(!isempty, [h[2] for h in hs])); isempty(ds) ? "—" : join(("`" * d * "`" for d in ds), ", ") end
    locs = join(("`" * l * "`" for l in unique(h[1] for h in hs)), ", ")
    mods = join(sort!(unique(String(first(split(h[1], ':'))) for h in hs)), ", ")
    println("| `", name, "` | ", dflt, " | ", locs, " | ", mods, " |")
end
println("\n", length(hits), " distinct flags across ", length(files), " files — generated by `tools/list_env_flags.jl`.")
